### ISSUE TITLE
我发现你这个有时候选择不了视频

### ISSUE THREAD

**Issue by lpwyz** [cmcy/media-selector#1]
你好，我发现用你这个视频选择器虽然可以进入视频选择页面，但是有时候选择不了视频。一点击，选择的事情，直接返回到主页面。

**Comment by cmcy** [comment]
有错误日志吗

**Comment by cmcy** [comment]
方便的话可以加我qq2537448950， 我这边上线的项目都是用的这个，还没反馈过有问题
